@startuml data-format-section-structured

skinparam backgroundColor white
skinparam handwritten false
skinparam defaultFontSize 10
skinparam classAttributeFontSize 9

skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

class DocumentReference {
  +subject : Reference~Patient~
  +date : dateTime
  +type : CodeableConcept
  +category : CodeableConcept
  +content : Bundle
  ...
}

class Bundle <<type: document>> {
}

class Composition <<first entry - for display purposes>> {
  +section : BackboneElement[]
  +section.text : Narrative
  ...
}

class DiagnosticReport <<for structured data>> {
  +presentedForm : Attachment~PDF~ (optional)
  ...
}

class ImagingStudy {
  ...
}

class ServiceRequest {
  ...
}

class Observation <<findings / measurements>> {
  ...
}


DocumentReference --> Bundle : content
Bundle --> Composition : entry[0]
Bundle --> DiagnosticReport : entry
Bundle --> ImagingStudy : entry
Bundle --> ServiceRequest : entry
Bundle --> Observation : entry
DiagnosticReport --> ImagingStudy : imagingStudy
DiagnosticReport --> ServiceRequest : basedOn
DiagnosticReport --> Observation : result

DiagnosticReport --> Composition : composition

@enduml
