@startuml data-format-basic-metadata

skinparam backgroundColor white
skinparam handwritten false
skinparam defaultFontSize 10
skinparam classAttributeFontSize 9

skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

class DocumentReference {
  +subject : Reference~Patient~
  +date : dateTime
  +type : CodeableConcept
  +category : CodeableConcept
  +content: Bundle
  ...
}

class Bundle <<type: collection>> {
}

class DiagnosticReport <<main resource>> {
  +presentedForm : Attachment~PDF~
  +imagingStudy : Reference~ImagingStudy~
  +basedOn : Reference~ServiceRequest~
  ...
}

class ImagingStudy <<optional in Bundle>> {
  +identifier : StudyInstanceUidIdentifierEuImaging
  ...
}

class ServiceRequest <<optional in Bundle>> {
  +identifier : AccessionNumberIdentifierEuImaging
  ...
}

class PDF <<attachment>> {
  +contentType : "application/pdf"
  +data : base64Binary
}

DocumentReference --> Bundle : content
Bundle --> DiagnosticReport : entry
Bundle --> ImagingStudy : entry (optional)
Bundle --> ServiceRequest : entry (optional)
DiagnosticReport --> PDF : presentedForm
DiagnosticReport --> ImagingStudy : imagingStudy
DiagnosticReport --> ServiceRequest : basedOn

@enduml
