@startuml

    package PatientHistory {
        class HeightObservation <<Observation>>
        class WeightObservation <<Observation>>
        class BloodPressureObservation <<Observation>>
        class HeartRateObservation <<Observation>>
    }

    package Findings {
        class WmsiRest01 <<Observation>>
    }

    HeightObservation --> Patient: subject
    WeightObservation--> Patient: subject
    BloodPressureObservation --> Patient: subject
    HeartRateObservation --> Patient: subject

    DiagnosticReport --> Composition: composition
    DiagnosticReport --> PDF: presentedForm
    DiagnosticReport --> Patient: subject
    DiagnosticReport --> Ultrasound: study
    DiagnosticReport --> Author: resultsInterpreter[author]
    DiagnosticReport --> UltrasoundCentrum: performer[organization]
    DiagnosticReport --> HeightObservation: extension[history]
    DiagnosticReport --> WeightObservation: extension[history]
    DiagnosticReport --> BloodPressureObservation: extension[history]
    DiagnosticReport --> HeartRateObservation: extension[history]
    DiagnosticReport --> ComeBackNextYearOrder: extension[recommendation]
    DiagnosticReport --> WmsiRest01: result

    Ultrasound --> Patient: subject
    Ultrasound --> RadiologyCentrum: series.performer

    Composition --> Patient: subject
    Composition --> DiagnosticReport: extension[diagnosticreport-reference]
    Composition --> Author: author[author]
    Composition --> UltrasoundCentrum: author[organization]
    Composition --> Ultrasound : entry[study].entry
    
    Composition --> HeightObservation: section[history].entry
    Composition --> WeightObservation: section[history].entry
    Composition --> BloodPressureObservation: section[history].entry
    Composition --> HeartRateObservation: section[history].entry

    Composition --> WmsiRest01: section[finding].entry

    Author --> UltrasoundCentrum: organization
    Author --> DvdJochemsen: practitioner

    class Author <<PractitionerRole>>
    class UltrasoundCentrum <<Organization>>
    class DvdJochemsen <<Practitioner>>


    class ComeBackNextYearOrder <<ServiceRequest>> {
        intent = #proposal
    }
    ComeBackNextYearOrder --> Patient : subject

    
    class WallMotionIndexScore <<Observation>>{
        valueQuantiry = ...
        component[].valueQuantiry = ...
    }
    WallMotionIndexScore --> Patient: subject
    WallMotionIndexScore --> Ultrasound: d
    class Patient{
        * name 
          * family = "Gutefrage"
          * given[+] = Test-Schust
    }
    class Ultrasound <<ImagingStudy>>  [[ImagingStudyStructuredReport1]] {
        * series[+] "stress"
        * series[+] "rest"
    }
    
    class PDF <<Binary>>

    class Composition [[./Composition-CompositionStructured.html]] {
        section[imagingstudy]
        * entry: LeftKnee
        * entry: RightKnee
        section[order]
        section[history]
        section[procedure]
        section[comparison]
        section[findings]
        * note: "..."
        section[findings]
        * note: "..."
        section[impressions]
        * note: "..."
    }

    class DiagnosticReport [[./DiagnosticReport-DiagnosticReportStructured.html]] {
        note[finding] = "..."
        note[finding] = "..."
        note[finding] = "..."
        note[finding] = "..."
        conclusion = "..."
    }
@enduml