@startuml

    package PatientHistory {
        class HeightObservation <<Observation>>
        class WeightObservation <<Observation>>
        class BloodPressureObservation <<Observation>>
        class HeartRateObservation <<Observation>>
    }

    HeightObservation --> Patient: subject
    WeightObservation--> Patient: subject
    BloodPressureObservation --> Patient: subject
    HeartRateObservation --> Patient: subject

    DiagnosticReport --> Composition: composition
    DiagnosticReport --> Patient: subject
    DiagnosticReport --> BloodPressureObservation: extension[history]
    DiagnosticReport --> HeartRateObservation: extension[history]
    DiagnosticReport --> ComeBackNextYearOrder: extension[recommendation]

    Composition --> Patient: subject
    Composition --> DiagnosticReport: extension[diagnosticreport-reference]  
    Composition --> HeightObservation: section[history].entry
    Composition --> WeightObservation: section[history].entry
    Composition --> BloodPressureObservation: section[history].entry
    Composition --> HeartRateObservation: section[history].entry

    class Patient{
        * name 
          * family = "Gutefrage"
          * given[+] = Test-Schust
    }

    class Composition [[./Composition-CompositionStructured.html]] {
    }

    class DiagnosticReport [[./DiagnosticReport-DiagnosticReportStructured.html]] {
    }
    
@enduml