@startuml
    DiagnosticReport --> Composition: composition
    DiagnosticReport --> PDF: presentedForm
    DiagnosticReport --> Patient: subject
    DiagnosticReport --> LeftKnee: study
    DiagnosticReport --> RightKnee: study
    DiagnosticReport --> Author: resultsInterpreter[author]
    DiagnosticReport --> RadiologyZentrum: performer[organization]
    
    LeftKnee --> Patient: subject
    LeftKnee --> RadiologyZentrum: series.performer
    RightKnee --> Patient: subject
    RightKnee --> RadiologyZentrum: series.performer

    Composition --> Patient: subject
    Composition --> DiagnosticReport: extension[diagnosticreport-reference]
    Composition --> Author: author[author]
    Composition --> RadiologyZentrum: author[organization]
    Composition --> LeftKnee : entry[study].entry
    Composition --> RightKnee: entry[study].entry
    
    Author --> RadiologyZentrum: organization
    Author --> LucasGassenzer: practitioner

    class Author <<PractitionerRole>>
    class RadiologyZentrum <<Organization>>
    class LucasGassenzer <<Practitioner>>

    class Patient{
        * name 
          * family = "Gutefrage"
          * given[+] = Test-Schust
    }
    class LeftKnee <<ImagingStudy>>  [[./ImagingStudy-ImagingStudySemiStructuredReport1.html]] {
        * series[+] "PD FatSat 3D (1.0mm) sagittal"
        * series[+] "T1 (2.5mm) axial"
        * series[+] "T2 (2.5mm) axial"
        * series[+] "PDW FatSat (2.5mm) axial"
    }
    class RightKnee <<ImagingStudy>> [[./ImagingStudy-ImagingStudySemiStructuredReport2.html]] {
        * series[+] "PD FatSat 3D (1.0mm) sagittal"
        * series[+] "T1 (2.5mm) axial"
        * series[+] "T2 (2.5mm) axial"
        * series[+] "PDW FatSat (2.5mm) axial"    
    }
    
    class PDF <<Binary>>

    class Composition [[./Composition-CompositionSemiStructured.html]] {
        section[imagingstudy]
        * entry: LeftKnee
        * entry: RightKnee
        section[order]
        section[history]
        section[procedure]
        section[comparison]
        section[findings]
        * note: "..."
        section[findings]
        * note: "..."
        section[impressions]
        * note: "..."
    }

    class DiagnosticReport [[./DiagnosticReport-DiagnosticReportSemiStructured.html]] {
        note[finding] = "..."
        note[finding] = "..."
        conclusion = "..."
    }
@enduml